# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 1
    vb.name = "ctr-ub-2"
  end

config.vm.network "private_network", ip: "192.168.33.102"
config.vm.hostname = "ctr-ub-2"

end