# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 1
    vb.name = "mas-ub"
  end

config.vm.network "private_network", ip: "192.168.33.100"
config.vm.hostname = "mas-ub"
config.vm.synced_folder "vagrant-rsync/", "/home/rsync", create: true
config.vm.provision 'shell', path: 'provision.sh'
end